### ISSUE TITLE
ServerEmojis - Not adding context menu item

### ISSUE THREAD

**Issue by xenorio** [jakuski/ed_plugins#3]
The plugin does not add anything to the context menu. No error in console.

With my limited understanding of ED plugins i have tried to put a console.log into the monkeyPatch, but it does not show up in the console (not on load and not when the context menu is rendered). ED logs into the console that it has patched the module tho.

OS: Ubuntu 18.04
ED, the plugin, and Discord are in their newest versions

**Comment by jakub-studio** [comment]
Whilst I'm not on Linux, I don't appear to be having any of these issues.

The context menu item is adding itself just fine to guild context menu:
![image](https://user-images.githubusercontent.com/34782021/54821816-3e471b00-4c9b-11e9-9e96-af3ea200770a.png)

![image](https://user-images.githubusercontent.com/34782021/54821840-5028be00-4c9b-11e9-950d-d1ce426a4caf.png)
